# Site settings
title: Wxhao Blog
SEOTitle: 吴嘉图的博客 | Wxhao Blog
header-img: img/home-bg.jpg
email: wxhao911@vip.qq.com
description: "关于WEB开发、极客与吃货 | 吴嘉图，Web & Mobile Love | 这里是 @Wxhao吴嘉图 的个人博客，你的梦想是什么?"
keyword: "吴嘉图, Wxhao吴嘉图, Wxhao, @wxhao, 吴嘉图的博客, Wxhao Blog, 博客, 个人网站, 互联网, 后端, JAVA, 园园的老公"
url: "http://blog.wxhao2.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     wxhao911
zhihu_username:     wxhao911
github_username:    wxhao911
#twitter_username:  huxpro
facebook_username:  wxh3211738



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: wxhaolog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: blog.wxhao2.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一枚天真无邪善良纯真的程序员欧巴."
sidebar-avatar: /img/avatar-wxhao.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
